exclude: .*migrations\/.*
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: 'requirements.txt'
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
    language_version: python3.9.13
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
        name: isort (python)
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.0
    hooks:
    -   id: djlint-django
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        exclude: .*factories\.py
